### ISSUE TITLE
PhotoSwipe options

### ISSUE THREAD

**Issue by agungsb** [GopherLabsLtd/react-photoswipe#2]
PhotoSwipe does take options for its configuration. I see that I can't pass `options` props to the component. I learn that the component doesn't take any `options` props. But there is a hard-coded `options` instead. Is there any reason why? Isn't it better to let users define the `options` freely?

**Comment by theiliad** [comment]
Yes @agungsb those are definitely in the roadmap. Feel free to contribute that to the repo if you like!

**Comment by agungsb** [comment]
Hi @theiliad ,

I would love to contribute to this awesome repo. I think will jump to it by this weekend.

Cheers!
